FactoryBot.define do
  factory :summary do
    episode
    sections do
      [
        {
          "title" => "Introduction",
          "content" => "The host welcomes listeners and introduces the topic.",
          "start_time" => 0,
          "end_time" => 120
        },
        {
          "title" => "Main Discussion",
          "content" => "A deep dive into the subject matter with the guest.",
          "start_time" => 120,
          "end_time" => 2400
        },
        {
          "title" => "Conclusion",
          "content" => "Key takeaways and closing thoughts.",
          "start_time" => 2400,
          "end_time" => 3000
        }
      ]
    end
    quotes do
      [
        {
          "text" => "This is the most important thing I've learned this year.",
          "start_time" => 845,
          "end_time" => 852
        },
        {
          "text" => "Everyone should try this at least once.",
          "start_time" => 1523,
          "end_time" => 1528
        }
      ]
    end
    # searchable_text is auto-generated by before_save callback
    searchable_text { nil }
  end
end
